export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const RECEIVE_STATE = 'RECEIVE_STATE'
export const RECEIVE_STATE_ERROR = 'RECEIVE_STATE_ERROR'
export const REQUEST_ACTION = 'REQUEST_ACTION'
export const DISABLE_BUTTONS = 'DISABLE_BUTTONS'

